/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":api"))
    implementation(project(":list"))
}

application {
    // Define the main class for the application.
    mainClass = "it.github.bankaccountmanager.app.App"
}
